// Project-level build.gradle file
buildscript {
    ext.kotlin_version = '1.7.20' // Replace with the version you want to use

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:8.0.2" // Ensure this is the correct version for your setup
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // Add other classpath dependencies here
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
